### ISSUE TITLE
Speed concerns

### ISSUE THREAD

**Issue by txj-xyz** [Night-Hunter-NF/apple-music-metadata#2]
I'm opening this due to overwhelming speed concerns.

Currently the time to look up a playlist with 87 songs in it on a server with 16 cores and 128GB of RAM takes over 55 seconds, is there any plans to improve the speed of things? 

I am considering profiling the code and making a pull with a redesign.

Thoughts?

**Comment by Night-Hunter-NF** [comment]
From what i have tested the issue is not to do with the actual code or computer but the way the code has to work to get info. this scrapes by getting the source metadata from the page which is pretty future proof as this is rarely changed (better than just reading the page). but for some reason i have yet to figure out, in playlists it does not have the artist in the metadata which means that for every song in playlist it has to go to that URL and find the artist.

I will look if this has changed when i have time. i am open to ideas.
i had thought about just scraping the page which is definitely faster by a lot but it would only take one change of code to stop it working vs this way where it would almost 100% of the time.

**Comment by txj-xyz** [comment]
Is it possible to attempt the fast method first? If that fails then revert over to the 100% working version?

For the sake of being a hybrid working attempt?

**Comment by Night-Hunter-NF** [comment]
i added the hybrid support for the playlists so the loading times have dropped dramatically. you can test it out on version 1.0.10

**Comment by txj-xyz** [comment]
So far all tests are passing on my end, performance is insane now.

Went from 55 sec --> 600ms

Good work! LGTM!
